config/routes.rb
Rails.application.routes.draw do
  resources :stories

  root "pages#index"
  get 'manage', to: 'stories#manage'
  post '/', to: 'pages#date'
  post 'stories/:id', to: 'pages#counting'
  get 'end', to: 'pages#end'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/story.rb
class Story < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def counting
    @story = Story.find(params[:id])
    @coupon = Coupon.last.quantity
    @coupon -= @story.weight
    if @coupon > 0
      Coupon.last.update(quantity: @coupon)
      redirect_to stories_path
    else
      Coupon.last.update(quantity: @coupon)
      redirect_to end_path
    end
    
  end

  def end 
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[ show edit update destroy ]
  before_action :date, only: [:index]

  # GET /stories or /stories.json
  def index
    @stories = Story.all
    @coupons = Coupon.last.quantity
    redirect_to end_path if @coupons <= 0
  end
  
  def manage
    @stories = Story.all    
  end

  # GET /stories/1 or /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories or /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to story_url(@story), notice: "Story was successfully created." }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to story_url(@story), notice: "Story was successfully updated." }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url, notice: "Story was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:title, :duration, :weight)
    end

    def date
      if !Coupon.where(:date => Time.now.to_date).present?
        @coupon = Coupon.new(:date => Time.now.to_date, :quantity => 60)
        @coupon.save
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TVapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/end.html.erb
<h1 class="header">You have used up all your coupons</h1>

app/views/pages/index.html.erb
<div class="home">
<%= link_to "Watch a TV show", stories_path, class:"button-4" %>
<%= link_to "Manage your shows", manage_path, class:"button-4" %>
</div>

app/views/stories/_form.html.erb
<div class="centerform">
  <%= form_with(model: story) do |form| %>
  <% if story.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <div class="input-container ic">
      <%= form.text_field :title, class:"input", placeholder: " " %>
       <div class="cut"></div>
      <%= form.label :title, class:"placeholder" %>
    </div>
      <div class="input-container ic">
        <%= form.text_field :duration, class:"input", placeholder: " " %>
         <div class="cut"></div>
        <%= form.label :duration, class:"placeholder" %>
      </div>

      <div class="input-container ic">
        <%= form.number_field :weight, class:"input", placeholder: " " %>
         <div class="cut"></div>
        <%= form.label :weight, class:"placeholder" %>
      </div>

      <div>
        <%= form.submit class:"submit" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/stories/_story.html.erb
<div id="<%= dom_id story %>">
  <h1>
    <%= story.title %>
  </h1>

  <p>
    <strong>Duration:</strong>
    <%= story.duration %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= story.weight %>
  </p>

</div>

app/views/stories/edit.html.erb
<h1 class="header">Editing story</h1>

<%= render "form", story: @story %>

<br>

<div class="buttons">
  <%= link_to "Show story", @story, class:"button-1" %>
  <%= link_to "Back to stories", manage_path, class:"button-1" %>
  <%= link_to "Back to home page", root_path, class:"button-1" %>
</div>

app/views/stories/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="header">
  <h1>You have <%= @coupons %> coupons left</h1>

  <progress value=<%= @coupons %> max="60"></progress>

  <h2>Select a show</h2>
</div>

<div class="shows">
  <% @stories.each do |story| %>
    <% if story.weight <= @coupons %>
      <%= button_to "", story, method: :counting, style:"background-image: url('/assets/#{story.title}.jpg');", class:"button-5" %>
    <% elsif story.weight > @coupons && story.weight < 10 %>
      <%= button_to "", story, method: :counting, style:"background-image: url('/assets/#{story.title}.jpg');", class:"button-5" %>
    <% end %>
  <% end %>
</div>

<div>
<%= link_to "Back to home page", root_path, class:"button-1" %>
</div>

app/views/stories/manage.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="header">Manage your shows</h1>
<div class="buttons">
  <%= link_to "New story", new_story_path, class:"button-1" %>
  <%= link_to "Back to home page", root_path, class:"button-1" %>
</div>
<div id="stories">
  <% @stories.each do |story| %>
    <div class="stories">
      <%= link_to story.title, story, style:"background-image: url('/assets/#{story.title}.jpg');", class:"button-3" %>
    </div>
  <% end %>
</div>

app/views/stories/new.html.erb
<h1 class="header">New story</h1>

<%= render "form", story: @story %>

<br>

<div class="buttons">
  <%= link_to "Back to stories", manage_path, class:"button-1" %>
  <%= link_to "Back to home page", root_path, class:"button-1" %>
</div>

app/views/stories/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="header">
<%= render @story %>
</div>

<div class="buttons">
  <%= link_to "Edit this story", edit_story_path(@story), class:"button-2" %>
  <%= link_to "Destroy this story", @story, data: { turbo_method: :delete }, class:"button-2" %>
</div>
<div class="buttons">
  <%= link_to "Back to stories", manage_path, class:"button-1" %>
  <%= link_to "Back to home page", root_path, class:"button-1" %>
</div>